### ISSUE TITLE
[Feature request] 能添加图标支持吗

### ISSUE THREAD

**Issue by Cierra-Runis** [fluttercandies/flutter_qweather#10]
### Platforms

Android, iOS, macOS, Web, Windows, Linux

### Description

如标题所示

### Why

当然是为了更方便啦

**Comment by CyJaySong** [comment]
要怎么个支持法？IconData?

**Comment by Cierra-Runis** [comment]
> 要怎么个支持法？IconData?

json里返回的图标代码和一个个IconData对应，大概（？）

**Comment by CyJaySong** [comment]
IconData 常量呗。。。

**Comment by Cierra-Runis** [comment]
看起来本库暂时还没有实观这个功能的想法，那么这里先自行关闭 issue 了

**Comment by CyJaySong** [comment]
为啥一直执着于这个库里添加图标呢😂

**Comment by Cierra-Runis** [comment]
> 为啥一直执着于这个库里添加图标呢😂

没关系，我自己写了个 [qweather_icons](https://github.com/Cierra-Runis/qweather_icons) 包，这个仓库可以引个流 😋

**Comment by CyJaySong** [comment]
@Cierra-Runis 提个PR吧，在这个库的README加个你的库的链接，放这里别人不容易看到
