### ISSUE TITLE
什么时候支持空气质量丫😀

### ISSUE THREAD

**Issue by ICE99125** [fluttercandies/flutter_qweather#3]

**Comment by ICE99125** [comment]
顺便提一个小问题
WeatherHourly 里的 windScaley = map['windScaley'] ?? ''; 可能要改成 map['windScale']
保持原来的时候风力显示不出来
比较菜就不 pr 了🤣

**Comment by ICE99125** [comment]
顺便提一个小问题
WeatherHourly 里的 windScaley = map['windScaley'] ?? ''; 可能要改成 map['windScale']
保持原来的时候风力显示不出来
比较菜就不 pr 了🤣

**Comment by CyJaySong** [comment]
@ICE99125 好的，下周吧，这周忙

**Comment by CyJaySong** [comment]
@ICE99125

**Comment by ICE99125** [comment]
感谢（。＾▽＾）

**Comment by CyJaySong** [comment]
@ICE99125 先试试，我家里没ios设备，帮我测一下预警接口
