### ISSUE TITLE
air_api报错

### ISSUE THREAD

**Issue by layingdownsmoke** [fluttercandies/flutter_qweather#4]
Unhandled Exception: MissingPluginException(No implementation found for method GetAirNow on channel com.fluttercandies.qweather)
初始化，查看今天和近三天的天气能成功运行。

**Comment by CyJaySong** [comment]
@layingdownsmoke 好的，我明天看看

**Comment by CyJaySong** [comment]
@layingdownsmoke  有实现啊，你看看你用的哪个版本？

**Comment by layingdownsmoke** [comment]
啊，对不起，我引入andorid文件的apiair
