### ISSUE TITLE
我有几个问题

### ISSUE THREAD

**Issue by layingdownsmoke** [fluttercandies/flutter_qweather#5]
为什么kotlin要和java混用呢。我不太明白。
引入项目后，andoridstudio可以识别dart和kotlin文件，但是不能识别java，也不能创建java文件。

一个工程是不是只能引入一个sdk呢，我尝试引入高德地图sdk来定位，可是会闪退，我完全不知道为什么。

**Comment by CyJaySong** [comment]
@layingdownsmoke 
混用的原因，主要是我想在onMethodCall函数路由时，使用kt的语法糖，Java 写起来很啰嗦。
AndoridStudio 新建没有Java , 你可以尝试在Project Structure-> Modules -> Sources 设置一下
一个工程可以引入多个SDK，崩溃跟数量无关，可能是你集成高德SDK时，某些地方没搞好，比如，混淆什么的

**Comment by layingdownsmoke** [comment]
谢谢你
