### ISSUE TITLE
Android获取不到天气信息

### ISSUE THREAD

**Issue by szuwest** [fluttercandies/flutter_qweather#7]
获取天气信息失败：没有任何报错
手机型号：iQOO Neo5
系统版本：Android 12
flutter_qweather版本：
0.0.9，0.0.6都不行

其他Android手机没问题，iOS也没问题。就发现一台手机有问题。没有任何报错日志。。

**Comment by CyJaySong** [comment]
这个很大可能跟插件无关😂
