### ISSUE TITLE
不支持iOS模拟器调试吗

### ISSUE THREAD

**Issue by szuwest** [fluttercandies/flutter_qweather#8]
目前我的工程运行iOS模拟器，qweather报错，开来是没有包含模拟器的编译文件。
error：
Undefined symbols for architecture x86_64:、

**Comment by CyJaySong** [comment]
似乎是SDK不支持

**Comment by CyJaySong** [comment]
我现在调试项目，也为此烦死嘞

**Comment by szuwest** [comment]
> 目前我的工程运行iOS模拟器，qweather报错，开来是没有包含模拟器的编译文件。 error： Undefined symbols for architecture x86_64:、

我看了工程，原来是QWeather sdk集成的方式不对。因为作者采样的是手动集成和风官方提供的QWeather SDK，但是官方提供的静态库是分真机、模拟器登不同平台的，作者并没有把这些库合并到一起。所以解决方法也很简单，就是手动把官方提供的几个iOS的SDK合并到一个就行了。当然也有一种简单的方法，采用cocoapods才集成QWeather SDK。我的fork就采用了这种方式。
修改flutter_qweather.podspec一下就行。

````
#  s.vendored_frameworks = 'QWeather.framework'
s.dependency 'QWeather-SDK'
s.static_framework = true

````

我的fork https://github.com/szuwest/flutter_qweather.git
已经测试过可以模拟器调试

**Comment by szuwest** [comment]
如果作者没更新，着急可以使用我的fork：

````
flutter_qweather:
    git:
      url: https://github.com/szuwest/flutter_qweather.git
````

**Comment by CyJaySong** [comment]
@szuwest 之前和风官方没得cocoapods库😂
